### ISSUE TITLE
Messaging example broken

### ISSUE THREAD

**Issue by kenfinnigan** [wildfly-swarm/wildfly-swarm-examples#31]
I know there's been a lot of change in the messaging API recently, so this was bound to happen.

Running on Alpha5 I get the following error on startup:

ERROR [org.jboss.as.controller.management-operation] (ServerService Thread Pool -- 5) WFLYCTL0013: Operation ("add") failed - address: ([
    ("subsystem" => "messaging-activemq"),
    ("server" => "default")
]) - failure description: "WFLYCTL0115: [0] is an invalid size for parameter incoming-interceptors. A minimum length of [1] is required"
ERROR [org.jboss.as.controller.management-operation] (Controller Boot Thread) "WFLYCTL0193: Failed executing subsystem messaging-activemq boot operations"
ERROR [org.jboss.as.controller.management-operation] (Controller Boot Thread) WFLYCTL0013: Operation ("parallel-subsystem-boot") failed - address: ([]) - failure description: "\"WFLYCTL0193: Failed executing subsystem messaging-activemq boot operations\""

**Comment by bobmcwhirter** [comment]
I was able to reproduce this.  Dunno what's up. Looking now.

**Comment by baboune** [comment]
Seeing same error with example.

topic entries: []
queeu entries: []
tmpDir: /tmp
16:10:04,464 INFO  [org.jboss.msc] (main) JBoss MSC version 1.2.6.Final
16:10:04,598 INFO  [org.jboss.as] (MSC service thread 1-7) WFLYSRV0049: WildFly Core 2.0.0.CR8 "Kenny" starting
16:10:05,049 ERROR [org.jboss.as.controller.management-operation] (ServerService Thread Pool -- 11) WFLYCTL0013: Operation ("add") failed - address: ([
    ("subsystem" => "messaging-activemq"),
    ("server" => "default")
]) - failure description: "WFLYCTL0115: [0] is an invalid size for parameter incoming-interceptors. A minimum length of [1] is required"
16:10:05,050 ERROR [org.jboss.as.controller.management-operation] (Controller Boot Thread) "WFLYCTL0193: Failed executing subsystem messaging-activemq boot operations"
16:10:05,051 ERROR [org.jboss.as.controller.management-operation] (Controller Boot Thread) WFLYCTL0013: Operation ("parallel-subsystem-boot") failed - address: ([]) - failure description: "\"WFLYCTL0193: Failed executing subsystem messaging-activemq boot operations\""
16:10:05,053 FATAL [org.jboss.as.server] (Controller Boot Thread) WFLYSRV0056: Server boot has failed in an unrecoverable manner; exiting. See previous messages for details.
16:10:05,054 ERROR [stderr] (main) Exception in thread "main" java.util.concurrent.ExecutionException: Operation failed
16:10:05,054 ERROR [stderr] (main) 	at org.jboss.threads.AsyncFutureTask.operationFailed(AsyncFutureTask.java:74)
16:10:05,054 ERROR [stderr] (main) 	at org.jboss.threads.AsyncFutureTask.get(AsyncFutureTask.java:268)
16:10:05,055 ERROR [stderr] (main) 	at org.jboss.as.server.SelfContainedContainer.start(SelfContainedContainer.java:113)
16:10:05,055 ERROR [stderr] (main) 	at org.wildfly.swarm.container.runtime.RuntimeServer.start(RuntimeServer.java:173)
16:10:05,055 ERROR [stderr] (main) 	at org.wildfly.swarm.container.Container.start(Container.java:298)
16:10:05,055 ERROR [stderr] (main) 	at com.ericsson.jmstokafka.JMSToKafkaMain.main(JMSToKafkaMain.java:43)
16:10:05,055 ERROR [stderr] (main) 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
16:10:05,055 ERROR [stderr] (main) 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
16:10:05,055 ERROR [stderr] (main) 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
16:10:05,056 ERROR [stderr] (main) 	at java.lang.reflect.Method.invoke(Method.java:497)
16:10:05,055 INFO  [org.jboss.as.server] (Thread-3) WFLYSRV0220: Server shutdown has been requested.
16:10:05,056 ERROR [stderr] (main) 	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
16:10:05,056 ERROR [stderr] (main) Caused by: java.lang.Exception: WFLYSRV0056: Server boot has failed in an unrecoverable manner; exiting. See previous messages for details.
16:10:05,056 ERROR [stderr] (main) 	at org.jboss.as.server.BootstrapListener.bootFailure(BootstrapListener.java:87)
16:10:05,056 ERROR [stderr] (main) 	at org.jboss.as.server.ServerService.boot(ServerService.java:384)
16:10:05,056 ERROR [stderr] (main) 	at org.jboss.as.controller.AbstractControllerService$1.run(AbstractControllerService.java:299)
16:10:05,056 ERROR [stderr] (main) 	at java.lang.Thread.run(Thread.java:745)
16:10:05,066 INFO  [org.jboss.as] (MSC service thread 1-7) WFLYSRV0050: WildFly Core 2.0.0.CR8 "Kenny" stopped in 7ms


What is this size for?

**Comment by bobmcwhirter** [comment]
I’ve fixed this in HEAD a few weeks back, I think.

**Comment by bobmcwhirter** [comment]
it’s because config-api at one point was including empty Lists for
non-defined things, instead of just skipping that property/resource.

**Comment by baboune** [comment]
Running the example with <version.wildfly-swarm>1.0.0.Alpha5</version.wildfly-swarm> triggers the problem.

**Comment by baboune** [comment]
Is it only 1.0.0.Alpha6-SNAPSHOT  that fixes this? No stable release?

**Comment by bobmcwhirter** [comment]
Maybe?  It might still be broken in Alpha6, but I didn’t think we released
Alpha5 with it broken but it’s entirely possible.  If you could confirm
against HEAD of github, we might have other problems causing the same
behavior.

**Comment by baboune** [comment]
Well I pulled a few days ago, and have been trying to make this work.

The examples are broken if using the default pom.xml (1.0.0.Alpha6-SNAPSTHOT)then I get the following error:
```java
mvn clean wildfly-swarm:run
[INFO] Scanning for projects...
[WARNING] The POM for org.wildfly.swarm:wildfly-swarm-plugin:jar:1.0.0.Alpha6-SNAPSHOT is missing, no dependency information available
[WARNING] Failed to retrieve plugin descriptor for org.wildfly.swarm:wildfly-swarm-plugin:1.0.0.Alpha6-SNAPSHOT: Plugin org.wildfly.swarm:wildfly-swarm-plugin:1.0.0.Alpha6-SNAPSHOT or one of its dependencies could not be resolved: Could not find artifact org.wildfly.swarm:wildfly-swarm-plugin:jar:1.0.0.Alpha6-SNAPSHOT
[WARNING] The POM for org.wildfly.swarm:wildfly-swarm-plugin:jar:1.0.0.Alpha6-SNAPSHOT is missing, no dependency information available
[WARNING] Failed to retrieve plugin descriptor for org.wildfly.swarm:wildfly-swarm-plugin:1.0.0.Alpha6-SNAPSHOT: Plugin org.wildfly.swarm:wildfly-swarm-plugin:1.0.0.Alpha6-SNAPSHOT or one of its dependencies could not be resolved: Could not find artifact org.wildfly.swarm:wildfly-swarm-plugin:jar:1.0.0.Alpha6-SNAPSHOT
Downloading: http://repo.maven.apache.org/maven2/org/codehaus/mojo/maven-metadata.xml
Downloading: http://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-metadata.xml
Downloaded: http://repo.maven.apache.org/maven2/org/codehaus/mojo/maven-metadata.xml (20 KB at 148.9 KB/sec)
Downloaded: http://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-metadata.xml (13 KB at 96.4 KB/sec)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.455s
[INFO] Finished at: Thu Nov 12 16:25:30 CET 2015
[INFO] Final Memory: 10M/236M
[INFO] ------------------------------------------------------------------------
[ERROR] No plugin found for prefix 'wildfly-swarm' in the current project and in the plugin groups [org.apache.maven.plugins, org.codehaus.mojo] available from the repositories [local (/local/scratch/maven/repository), central (http://repo.maven.apache.org/maven2)] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/NoPluginFoundForPrefixException
```

And if I set the version to in the pom file such as:
```java
<version.wildfly-swarm>1.0.0.Alpha5</version.wildfly-swarm>
```
Then I get the above error with size.

Will try to clean local repository and pull again.

**Comment by baboune** [comment]
For my education, which git command should I run to get "HEAD of github"?

**Comment by bobmcwhirter** [comment]
The quickest:

git clone https://github.com/wildfly-swarm/wildfly-swarm.git
mvn install -DskipTests

Once you have it cloned, you can update to the latest via

git fetch origin
git rebase origin/master
mvn clean && mvn install -DskipTests

**Comment by emag** [comment]
@bobmcwhirter @baboune And FYI, adding `-T2` or `-T4` something may be useful. `-Tn` means it is enable to perform parallel builds(`n` is the number of the thread).

https://cwiki.apache.org/confluence/display/MAVEN/Parallel+builds+in+Maven+3

**Comment by samueltauil** [comment]
had the same issue using Alpha5, building SNAPSHOT now to test

**Comment by emag** [comment]
I guess this issue should be fixed at https://github.com/wildfly-swarm/wildfly-swarm/commit/1e9325d2c23134b7bc079f8c4be587f4bd0f9769 .

I checked it works with [WF-Swarm HEAD](https://github.com/wildfly-swarm/wildfly-swarm/commit/9cb95a4d836417497ab74e576dfb8e3c2042819d)

**Comment by samueltauil** [comment]
@emag working using Alpha6-SNAPSHOT version, thanks!

**Comment by baboune** [comment]
@bobmcwhirter Thanks for the help

I confirm that it works with HEAD.

Problem is only present in 1.0.0.Alpha5 repositories.

**Comment by kenfinnigan** [comment]
Closing as resolved
